server:
  port: 9999

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 嘻嘻嘻嘻嘻
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatemetns: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password: xiaopeng
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 100
      min-idle: 1

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    password: hahahahha
    port: 25
    protocol: smtp
    username: xxxxxxxxx@163.com


# mybatis 的相关配置
mybatis:
  mapper-locations: classpath:mapping/*.xml # mybatis 映射文件
  type-aliases-package: com.pengchant.model # 对应实体类的路径

# pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# mytoken
mytoken:
  appkey: 978dfsa7fc3a34e1261dsafec1245d
  ttlmillis:  1800000 # 测试设置30min过期1800000

# myemail
myemail:
  from: sxxxxxxxxx@163.com
  subject1: 我的博客网站验证码
  subject1pre: 你好，欢迎你注册博客网，你的验证码为：
  subject2end: 谢谢您的支持！请尽快完成注册，验证码将在30分钟后失效！


# img
img:
  location: /usr/local/myblog-img


